#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveTilesWidget.Resource", IsApplication=true)]

namespace LiveTilesWidget
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int btnChooseApp = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int btnRefresh = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int checkAutoColor = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int checkShowNotif = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int item_app_icon = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int item_app_label = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int listTiles = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int textView1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView3 = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int tileBackground = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tileIcon = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int tileLabel = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int tileNotifParent = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int tileNotification = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int tileRoot = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppPickerItems = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NormalTile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TileSettings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int normal_tile = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
